name: tepung
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.2
  golden_toolkit: ^0.9.0

flutter:
  fonts:
    - family: MaisonNeue
      fonts:
        - asset: assets/fonts/maison_neue_book.otf
          weight: 400
        - asset: assets/fonts/maison_neue_demi.otf
          weight: 600
        - asset: assets/fonts/maison_neue_bold.otf
          weight: 700
  assets:
    - assets/icons/icActions16Add.svg